version: "3.9"

services:
  db:
    image: postgres:15.4-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: healthcheck
    restart: always
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - API_KEY=${API_KEY}
      - ALG=${ALG}
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules
volumes:
  db:
    driver: local 